sonar.projectKey=SenSeTioN_go-project-244
sonar.organization=sensetion

sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,bin/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
